### ISSUE TITLE
CANT WORK

### ISSUE THREAD

**Issue by hanwenbo** [awesomejerry/react-native-qrcode-svg#76]
error: bundling failed: Error: While trying to resolve module `react-native-svg` from file `projectPath/node_modules/react-native-qrcode-svg/src/index.js`, the package `projectPath/node_modules/react-native-svg/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`projectPath/node_modules/react-native-svg/src/index.ts`. Indeed, none of these files exist:

 * `projectPath/node_modules/react-native-svg/src/index.ts(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `projectPath/node_modules/react-native-svg/src/index.ts/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (projectPath/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:103:15)
    at DependencyGraph.resolveDependency (projectPath/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at projectPath/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by hanwenbo** [comment]
The package version is not correct. You need to manually change the package version of SVG
